
export const LEVELS: string[] = [
    'Level 1 - Survival (A1-A2): Người mới bắt đầu',
    'Level 2 - Functional (B1): Giao tiếp cơ bản',
    'Level 3 - Professional (B2): Giao tiếp công việc',
    'Level 4 - Fluent (C1): Thành thạo',
    'Level 5 - Native-like (C2): Như người bản xứ'
];

export const TOPICS: string[] = [
    'A. CUỘC SỐNG HÀNG NGÀY:',
    '1. Giới thiệu & Làm quen',
    '2. Gia đình & Mối quan hệ',
    '3. Nhà ở & Sinh hoạt',
    '4. Mua sắm (siêu thị, quần áo, điện tử)',
    '5. Ăn uống (nhà hàng, cafe, nấu ăn)',
    '6. Giao thông (hỏi đường, taxi, xe bus)',
    '7. Sức khỏe (bệnh viện, khám bệnh, thuốc)',
    '8. Du lịch (khách sạn, sân bay, tham quan)',
    '9. Giải trí (phim, nhạc, thể thao, sở thích)',
    '10. Thời tiết & Môi trường',
    'B. HỌC TẬP & PHÁT TRIỂN:',
    '11. Trường học & Giáo dục',
    '12. Thi cử & Chứng chỉ',
    '13. Học online & Công nghệ',
    '14. Đọc sách & Nghiên cứu',
    '15. Thuyết trình & Báo cáo',
    '16. Thảo luận nhóm',
    '17. Phỏng vấn học bổng',
    '18. Viết luận văn & Paper',
    'C. CÔNG VIỆC & SỰ NGHIỆP:',
    '19. Phỏng vấn xin việc',
    '20. CV & Cover letter (nói về)',
    '21. Họp & Meeting (chủ trì, tham gia)',
    '22. Email & Giao tiếp công việc',
    '23. Thương lượng & Đàm phán',
    '24. Quản lý & Lãnh đạo',
    '25. Làm việc nhóm & Collaboration',
    '26. Khách hàng & Dịch vụ',
    '27. Báo cáo tiến độ',
    '28. Đánh giá hiệu suất',
    '29. Xin nghỉ phép & Xử lý vấn đề',
    '30. Networking & Mối quan hệ nghề nghiệp',
    'D. CHUYÊN MÔN (Theo ngành):',
    '31. Công nghệ thông tin (code, debug, system)',
    '32. Marketing & Sales',
    '33. Tài chính & Kế toán',
    '34. Y tế & Dược',
    '35. Kỹ thuật & Xây dựng',
    '36. Luật & Pháp lý',
    '37. Nghệ thuật & Thiết kế',
    '38. Khoa học & Nghiên cứu',
    '39. Giáo dục & Đào tạo',
    '40. Logistics & Vận tải',
    'E. XÃ HỘI & VĂN HÓA:',
    '41. Tin tức & Thời sự',
    '42. Chính trị & Kinh tế',
    '43. Văn hóa & Lịch sử',
    '44. Tranh luận & Phân tích',
    '45. Xu hướng xã hội',
    '46. Vấn đề môi trường',
    '47. Công nghệ & Tương lai',
    '48. Nghệ thuật & Văn học',
    '49. Tôn giáo & Triết học',
    '50. Small talk & Chit-chat',
    'F. TÌNH HUỐNG ĐẶC BIỆT:',
    '51. Khẩn cấp (mất đồ, gặp nạn)',
    '52. Khiếu nại & Giải quyết tranh chấp',
    '53. Khen ngợi & Phê bình',
    '54. Xin lỗi & Giải thích',
    '55. Đồng cảm & An ủi',
    '56. Đùa cợt & Hài hước',
    '57. Tranh luận & Bảo vệ quan điểm',
    '58. Thuyết phục & Ảnh hưởng',
    '59. Tư vấn & Góp ý',
    '60. Storytelling & Kể chuyện'
];
